name: 'Build'
description: 'Build a Java project using Gradle'
inputs:
  java-distribution:
    description: 'Java distribution to use'
    required: false
    default: 'microsoft'
  java-version:
    description: 'Java version to use'
    required: false
    default: '17'
  gradle-version:
    description: Gradle version to use
    required: false
    default: 'wrapper'
  arguments:
    description: Gradle command line arguments
    required: false
    default: 'check bootJar'
  package-name:
    description: 'The name of the uploaded package'
    required: false
    default: 'package'
  package-path:
    description: 'The path to the package files to be uploaded'
    required: false
    default: '${{ github.workspace }}/build/libs/*.[j,w]ar'
runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v3
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: ${{ inputs.gradle-version }}
    - name: Execute Gradle build
      run: ./gradlew ${{ inputs.arguments }}
      shell: bash
    - name: Upload package
      uses: actions/upload-artifact@v4
      if: inputs.package-path != ''
      with:
        name: ${{ inputs.package-name }}
        path: ${{ inputs.package-path }}
        retention-days: 1
