name: 'Build'
description: 'Build a Java project using Gradle'
inputs:
  java-version:
    description: 'The Java version'
    required: false
    default: '17'
  gradle-version:
    description: Gradle version to use
    required: false
    default: 'current'
  arguments:
    description: Gradle command line arguments
    required: false
    default: 'check bootJar'
  package-name:
    description: 'The artifact name for the uploaded package'
    required: false
    default: 'package'
  package-path:
    description: 'The path to the package files to be uploaded'
    required: false
    default: '${{ github.workspace }}/build/libs/*.[j,w]ar'
runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: microsoft
        java-version: ${{ inputs.java-version }}
    - name: Setup and build with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: ${{ inputs.gradle-version }}
        arguments: ${{ inputs.arguments }}
    - name: Temporarily save package
      uses: actions/upload-artifact@v4
      if: inputs.package-path != ''
      with:
        name: ${{ inputs.package-name }}
        path: ${{ inputs.package-path }}
        retention-days: 1
