name: 'Deploy a Java application to Azure App Service'
description: 'Deploy a Java application to Azure App Service'
inputs:
  azure_credentials:
    description: 'Azure Credentials, stored in a secret on your GitHub repository.'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download Terraform output data
      uses: actions/download-artifact@v3
      with:
        name: terraform-output
    - name: Set environment variables
      run: |
        echo "APPLICATION_CAF_NAME=$(cat terraform-output.json | jq -r .application_caf_name.value)" >> $GITHUB_ENV
        echo "RESOURCE_GROUP_NAME=$(cat terraform-output.json | jq -r .resource_group_name.value)" >> $GITHUB_ENV
      shell: bash
    - name: Download application package
      uses: actions/download-artifact@v3
      with:
        name: package
        path: app-package
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APPLICATION_CAF_NAME }}
        package: 'app-package/*.[j,w]ar'
    - name: Restart Azure App Service
      run: |
        az webapp restart --name ${{ env.APPLICATION_CAF_NAME }} --resource-group ${{ env.RESOURCE_GROUP_NAME }}
      shell: bash
