name: 'Build'
description: 'Build a Java project using Ant'
inputs:
  java_version:
    description: 'The Java version'
    required: false
    default: '11'
  build_command:
    description: 'The command to build the Java project'
    required: false
    default: 'ant -noinput -buildfile build.xml'
  package_path:
    description: 'The path to the generated package, to be uploaded on the last step'
    required: false
    default: '${{ github.workspace }}/target/*.[j,w]ar'
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}
        check-latest: false
    - name: Build with Ant
      run: ${{ inputs.build_command }}
      shell: bash
    - name: Temporarily save package
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: ${{ inputs.package_path }}
        retention-days: 1
